[package]
name = "poc-rust-dip"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
postgres = { version = "0.19.4", features = ["with-chrono-0_4"] }

[dev-dependencies]
testcontainers = "0.14.0"
assert_cmd = "2.0.4"
predicates = "2.1.1"